### ISSUE TITLE
[BUG] When multiple wallets are connected, the Manage Positions page currently displays fake data instead of retrieving information from the respective wallets.

### ISSUE THREAD

**Issue by esot321c** [coinecta/coinecta-frontend#71]

**Comment by esot321c** [comment]
One thing you can do to prevent it from looking funny is just to make sure the skeleton continues to show. As you can see in total value staked, it keeps showing the skeleton, but the positions list resolves to dummy data. 

This doesn't address the underlying issue, but it will make a better UX when this issue arises. 

![Image](https://github.com/coinecta/coinecta-frontend/assets/86281023/bf76ed72-2241-4025-bb5f-2a9f4ce11785)

**Comment by phonz-dev** [comment]
Thanks for the suggestion. I'll implement this solution. Appreciate your guidance on this!

**Comment by esot321c** [comment]
If we know there are no positions, maybe it's better to say "no positions found" instead of continue to display a loading state. 

Same with in other areas. Once the load is complete, just show a dash when number values aren't available. 

This seems nicer, what do you think?

**Comment by esot321c** [comment]
And if the query fails, show "unable to load position data. Check that wallets are synced with the blockchain" 

Or something like this
